modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "Apache 2.0"

[[mods]]
modId = "cottages"
version = "${version}"
displayName = "Cottages"
authors = "Nehlen"
description = '''
A mod that adds small cottage structures in a forest for a more alive world.
'''
#logoFile = ""

[[dependencies.cottages]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cottages]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "cottages.mixins.json"
